### PR TITLE
1224 - Tapestry 3.0 - User-facing UI redesign

### LINKED ISSUE #1224: Main UI redesign
A redesign of the main UI that will put the toolbar on top of the Tapestry view instead of above it, and make sure that Tapestry view occupies full screen real-estate so the toolbar and minimap are visible at the same time.

### PR DESCRIPTION
**Pull request by legendword**
## Changes
* Restrict app height as to not have an overflown body, thus achieving a fullscreen experience while keeping the Wordpress header and footer visible.
* Minimap size is now set to 20% of the Tapestry view size.
* Rename toolbar to menubar to differentiate between the bar on the top and the toolbar on the left which will be added in #1227.
* Display title of tapestry on the top left.
* Overlay the menubar and title on top of the main Tapestry view, so content can go below them.
* Move tapestry depth slider to the bottom right, beside the minimap. The depth slider is now vertical.
* Move tapestry filter button to the right, besides the menubar. The filter button and the menubar have separate backgrounds.
* Move view user answers button into the triple dot operations button in the menubar to save space.
* Hide the review notifications button in the menubar if there are no nodes awaiting review.
* Add the depth indicator beside the depth slider, showing layers of levels that are reactive to the user's current zoom level.
* Improve the positioning of the add node button, import button, and the import file dropbox when the tapestry is empty.
* Scrolling the page will zoom the tapestry, without the need to press any modifier keys.

## Screenshot
(outdated)
image

## Issue Linkage
Closes #1224 
## PR Dependency
Depends on: #1259 
## Automated Testing
* N/A

### CODE REVIEW

**Comment by legendword** [comment]
Audited accessibility on the changes made in this PR:

- Tapestry depth indicator layers do not have a descriptive title.
- Minimap toggle button has no descriptive title - will fix in #1199.
- Tapestry title is a normal text element with no context describing that it is the title of the Tapestry.
- Menubar still reads out to be "Tapestry Menubar, empty group" when all its content is hidden - will fix by applying v-if to the whole menubar.

**Comment by zifgu** [comment]
> * Tapestry title is a normal text element with no context describing that it is the title of the Tapestry.

Changed to an h1 since this page (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role) recommends using h1-h6 over the 'heading" role. Let me know if you had something else in mind.

> * Menubar still reads out to be "Tapestry Menubar, empty group" when all its content is hidden - will fix by applying v-if to the whole menubar.

Made the change, which should fix this.

**Comment by Bitajkr** [comment]
- [ ] I just noticed some weird bugginess on the following site: https://test.tapestry-tool.com/1198-accessibility/tapestry/tapestry-tool-3-0-study-numbers/#/nodes/314

Are you currently making some changes on this site?

**Comment by Bitajkr** [comment]
@legendword I noticed that the title was cut off for one of the nodes that I had with a longer title. I wasn't too sure where to report this so I am noting it here. 

Screen Shot 2022-12-06 at 3 37 08 PM

**Comment by wynnset** [comment]
> @legendword I noticed that the title was cut off for one of the nodes that I had with a longer title. I wasn't too sure where to report this so I am noting it here.
> 
> This is in the newest alpha release: https://test.tapestry-tool.com/tapestry-alpha/tapestry/hierarchy-of-food/#/nodes/541

@Bitajkr I think this is something that's been there for a long time and not related to this PR. I recommend adding a space before/after the "/" in order to have it break since the line break happens on the space character usually.

**Pull request closed without merging**
