### PR TITLE
1198 - Tapestry 3.0 - Better accessibility

### LINKED ISSUE #1198: Better accessibility

### PR DESCRIPTION
**Pull request by legendword**
#### Styling

* Remove `outline: none;` CSS styles such that outlines for keyboard navigation users shows up for better accessibility.
* Elements should have `:focus` styles similar to their `:hover` styles, if they have any.

#### Descriptive text for screen readers

* All interactive elements have descriptive text labels for screen readers (`aria-label`), and should be focusable and announced as the correct type of element (by explicitly setting the `role` attribute on some interactive elements).
* Describe modals gracefully and ensure everything in the modal can be accessed by the screen reader.
* Describe nodes gracefully and provide information on how to navigate the nodes for screen readers via `aria-label`.
  * Example text description for a node named Introduction: "Introduction. You are on a level 1 node. This node has 3 children. To view this node, press Enter. To go to its first child, press the Down Arrow Key. To go back up, press the Up Arrow Key. To go to its siblings, press the Left or Right Arrow Key."
* Use `aria-live` for error messages so that they are immediately announced by the screen reader.

#### Focus management

* Improve tabbing behaviour when modal is open so that focus is trapped inside the modal; tabbing beyond the last focusable element will return the focus to the first focusable element and vice versa.
* Focus will return to the element that activated the modal upon closing.
* When a button that adds some elements onto the view is pressed (such as the "Add Condition" button in NodeModal access tab, and the "Add Question" button when editing an Activity node), the newly added element should receive focus automatically.
* Use the [roving tabindex method](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_roving_tabindex) for managing focus within the RichTextForm toolbar. When on an item in the toolbar, press Left / Right arrow keys to navigate to other menu items as outlined in the [W3 WAI-ARIA toolbar keyboard interaction guide](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/#keyboard-interaction-22).
* Also use the [roving tabindex method](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_roving_tabindex) for the main Tapestry view such that only one node or link is focusable at a time. This makes it easier to navigate into and out of the main Tapestry view, since the user only needs to press Tab **once** to focus on the next element in the document flow.
* Use [aria-activedescendant](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_focus_activedescendant) to manage focus for the Combobox component, as well as allow keyboard navigation of the combobox options list using Up / Down arrow keys & more as outlined in the [W3 WAI-ARIA combobox keyboard interaction guide](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#keyboard-interaction-6). Users should be able to view the list of suggested options, type into the input directly, and accept a suggested option using the keyboard and/or with the screen reader.

#### Main Tapestry view keyboard navigation

* Allow navigating nodes of the main Tapestry by keyboard. Up / Down / Left / Right arrow keys to traverse the tree hierarchy of the zoomable interface; Enter to view the node; E to edit the node; Q or Esc to exit the main Tapestry view.
* Allow navigating the links of the main Tapestry by keyboard when the user is logged in. Enter the link navigation mode by holding down Shift and pressing Up / Down arrow keys to go to the link connecting the current node to its parent / child, respectively. Then, Left / Right arrow keys will focus the sibling links, Enter / E will open the link modal for editing, and Up / Down arrow keys will exit the link navigation mode.

### Other changes

* Use `<b-modal>` for lightbox, since the Bootstrap modal component has great accessibility features (most important one being tab trapping, ensuring user cannot tab out of the modal).
* UrlVideoMedia now correctly resizes the Lightbox to fit the video (did not work properly before this PR).
* Full screen videos are now properly fit to the screen.
* Fix flaky test in user-settings.spec.js by not force clicking the buttons.
* Make browserDimensions responsive, so full screen videos are still being fit to the screen when resizing the browser window.
* Remove all instances of the `data-testid` attribute, since this attribute is no longer used for testing.

(Refer to https://www.deque.com/blog/give-site-focus-tips-designing-usable-focus-indicators/ for focus indicator best practices.)

## Screenshot
* Todo
## Issue Linkage
Closes #1198 
## PR Dependency
Depends on: #1191 
## Automated Testing

Due to the limitations of [Cypress](https://docs.cypress.io/api/commands/type), which does not allow us to realistically test browser keyboard focus and navigation functionality, it's best for testers to test this PR using their own browser environment. Ensure your browser do not have anything that overrides the :focus-visible CSS pseudo-class, and try to navigate through all the tapestry on-screen elements by using tab.

You can tab forward by pressing TAB, go back to the previous element by pressing SHIFT+TAB. To activate and "click" an element, press ENTER. Clicking an element should yield identical behaviour as a mouse click. For modifying sliders, use your LEFT and RIGHT arrow keys.

### CODE REVIEW

**Comment by zifgu** [comment]
Tested the current functionality of this PR, as we discussed.
- The new lightbox works just as well as before.
- URL videos look a lot better now and are fit cleanly in the lightbox. Videos also work in fullscreen mode and resize properly with the window.
- Opening a modal or selecting a node reads the description, which is very clear. Describing only the available commands depending on the node's position in the hierarchy is an especially helpful addition.
- Keyboard navigation with Up/Down/Left/Right/Enter/E keys works both with and without a screen reader enabled. The navigation stack starts from the clicked node, so starting from a child makes it impossible to navigate up to its parent without clicking again. Focus returns to the node when the modal is closed.

**Accessibility features**:

Since I included images, making the review quite long, and to make it more open to feedback from the team since I'm new to screen reader software, you can find all accessibility-related comments on Notion in a new page under "Accessibility Audit".

While testing, I couldn’t manage to navigate the BTabs component in several of our modals using Narrator. The tabs did not seem to receive focus when tabbed or respond to pressing “Enter”. I also couldn’t manage to navigate the Combobox component using the arrow keys and “Enter”, which is used in multiple places (H5P nodes, WordPress post nodes, the Copyright field, etc). Could I just confirm that these are indeed navigable?

**Comment by legendword** [comment]
> starting from a child makes it impossible to navigate up to its parent without clicking again

I am aware of this; I was hesitant to add this ability due to the ambiguity when there are multiple "parent" nodes. When navigating down the tree, the parent is always known; but we will need to automatically choose a parent when navigating using the Tab or by clicking, since these do not follow the tree structure.

**Comment by zifgu** [comment]
Here is the link to my comments on Notion: https://www.notion.so/tapestrytool/1198-Better-accessibility-review-801b947f1cb9477289420984df868211

**Comment by legendword** [comment]
Implementing focus management for rich text form toolbar according to the following specifications from W3C:

https://w3c.github.io/aria/#toolbar

https://w3c.github.io/aria/#managingfocus

**Comment by legendword** [comment]
> While testing, I couldn’t manage to navigate the BTabs component in several of our modals using Narrator. The tabs did not seem to receive focus when tabbed or respond to pressing “Enter”. I also couldn’t manage to navigate the Combobox component, which is used in multiple places (H5P nodes, WordPress post nodes, the Copyright field, etc), using the arrow keys and “Enter”. Could I just confirm that these are indeed navigable?

On Mac Voiceover, I can focus on the BTabs component and I can use the arrow keys to switch to a different tab.

For the Combobox, I am also experiencing issues navigating it using the keyboard. I will fix this soon.

**Comment by zifgu** [comment]
> On Mac Voiceover, I can focus on the BTabs component and I can use the arrow keys to switch to a different tab.

Tried using arrow keys to navigate the tabs with the screen reader off, and it worked. I think Windows Narrator's scan mode might just be intercepting the arrow key inputs, and scan mode can be turned off. In that case, this should be figured out - thanks!

> For the Combobox, I am also experiencing issues navigating it using the keyboard. I will fix this soon.

Sounds good.

**Comment by legendword** [comment]
Made the Combobox component accessible, using **aria-activedescendant** for focus management, by referring to the following specifications:

https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-autocomplete-list.html

https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_focus_activedescendant

https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#keyboard-interaction-6

**Comment by legendword** [comment]
All requested changes in https://www.notion.so/tapestrytool/1198-Better-accessibility-review-801b947f1cb9477289420984df868211#a4b2242e27a34b578ed8e492a516e80b have been discussed and implemented. Please review and confirm that the accessibility problems are all addressed.

**Comment by zifgu** [comment]
> All requested changes in https://www.notion.so/tapestrytool/1198-Better-accessibility-review-801b947f1cb9477289420984df868211#a4b2242e27a34b578ed8e492a516e80b have been discussed and implemented. Please review and confirm that the accessibility problems are all addressed.

Thank you! Tested and confirmed that all of the suggestions have been fixed. This looks great.

**Pull request closed without merging**
