### PR TITLE
1187 - Bug fix: Node thumbnails added via link preview disappear on refresh

### LINKED ISSUE #1187: Bug: node thumbnails added via link preview disappear on refresh
**Branch**: Bug is found on #1167, currently the latest branch. Also present on the current master.

**Steps to reproduce:**
1. Create a video node and input a YouTube video URL.
2. Click "OK" to use the link preview image as the thumbnail image and locked thumbnail image. At this point, `imageURL` and `lockedImageURL` should contain the correct values. The thumbnail images can be seen in the Appearance tab.
3. Refresh the page.

**Expected behaviour**: The thumbnail images are still there.
**Actual behaviour**: The thumbnail images have disappeared. In the Vuex state, both `imageURL` and `lockedImageURL` are empty strings.

**Other cases**:
- Bug also occurs on External Link nodes
- Bug also occurs if you choose to set only one of the thumbnail and locked thumbnail image – both are set to empty strings

Bug does not occur when thumbnail or locked thumbnail image are manually uploaded via the Appearance tab.

https://user-images.githubusercontent.com/44929104/172746531-330eeba9-7de5-4a93-8cca-a7866b6cffaf.mp4

### PR DESCRIPTION
**Pull request by legendword**
## Changes
* Do not unset imageURL and lockedImageURL when fileId is empty.
* Unset the thumbnailFileId and lockedThumnailFileId when the user chooses to add thumbnails via link preview.
## Issue Linkage
Closes #1187 
## PR Dependency
Depends on: #1167
## Automated Testing
N/A

### CODE REVIEW

**Comment by wynnset** [comment]
Does this ensure that users can also remove the node thumbnail somehow using the authoring interface?

**Review by zifgu — CHANGES_REQUESTED** [review]
Based on testing, the thumbnail images that were added via link preview are accessible in the Appearance menu like regular images, and users are able to remove them.

However, I am encountering an issue where I can't remove thumbnail images that were added via upload:

https://user-images.githubusercontent.com/44929104/173471760-761dd865-cc24-4168-a759-9c20ef379585.mp4

**Comment by zifgu** [comment]
The new changes make a lot of sense. Tested and the above bug is fixed too.

However, I am finding a different bug when changing a node from manually uploaded thumbnails to link preview thumbnails.

https://user-images.githubusercontent.com/44929104/173714489-50841260-752e-4058-b5c9-c6455b4ea992.mp4


I think it's because the `fileId` is not unset when the user chooses to use link preview thumbnails.

**Review by zifgu — APPROVED** [review]
Looks good. Tested reproducing the above bugs, and they are both fixed. Thumbnails uploaded via the link preview dialog can be removed or edited in the Appearance window, which should be the expected behaviour.

**Review by wynnset — APPROVED** [review]

**Pull request merged**
