### PR TITLE
964 - Multi-Content Node: Adding slideshow display type

### LINKED ISSUE #964: Multi-Content Node; Adding slideshow display type

### PR DESCRIPTION
**Pull request by shirleywbi**
## Changes
* Add slideshow presentation style to multi-content
* Add checkbox to slideshow content forms to toggle main slideshow title
* Update multi-content getters to take additional validation function
* Refactor showTitle behaviour from individual *medias to TapestryMedia
## Screenshot
ezgif com-gif-maker (7)
## Issue Linkage
Closes #964 
## PR Dependency
Depends on: #971 
## Automated Testing
* should render, navigate unlocked slides, and disable nagivating to locked slides

### CODE REVIEW

**Comment by shirleywbi** [comment]
@wynnset Regarding titles, how do we want the titles to appear? Do we want to have the main title of the slideshow appear at top (underlined)? 
image

**Comment by wynnset** [comment]
> Regarding titles, how do we want the titles to appear? Do we want to have the main title of the slideshow appear at top (underlined)? 
> 

Let's have a toggle button to show or hide the title (default = hide)

If the choose to display it, we should display it similar to your screenshot so centred at the top of the slideshow.

**Comment by odotadot** [comment]
@wynnset Are the arrow buttons supposed to be inside the video screen (from the Asana specs) and not to the bottom-right corner?
image

**Comment by wynnset** [comment]
> Are the arrow buttons supposed to be inside the video screen (from the Asana specs) and not to the bottom-right corner?

Good catch @odotadot ! I would say let's **keep the arrows at the bottom right**, but to encourage the user to continue the slideshow, let's **replace the close (X) button with a right arrow, going to the next slide**. Note: The exception is for the last item in a slideshow. We can keep the close (X) button if it's the last item in the slideshow. Does that make sense?

**Comment by odotadot** [comment]
Yup, makes sense.

**Comment by harry02031** [comment]
One potential bug that I found is that when you have two video slides in a row, after you finish a video and you click the next arrow button to navigate to the next slide, the next slide will show that the video is already finished watching.

https://user-images.githubusercontent.com/30706624/118202597-1ed95200-b40f-11eb-8706-dd8fa8c6db58.mov

**Review by EldadZZipori — APPROVED** [review]
Code looks really good and tidy. All tests pass on local mechince and remotely, only test to fail remotely seems to be a video upload which works.

**Comment by wynnset** [comment]
This PR is obsolete. We will need to recreate this from scratch if we want this feature.

**Pull request closed without merging**
