### PR TITLE
1164 - Upgrade node packages and prepare for node v16

### LINKED ISSUE #1164: Upgrade node packages and prepare for node v16
Purpose:

- First to make sure all packages are up-to-date for security and compatibility with newer node versions
- Then to transition to using node v16 which is the current newest LTS

### PR DESCRIPTION
**Pull request by legendword**
## Changes
**The changes require running `npm install` to take effect.**
**Now using node v16. Please update your local node version as well.**
- update webpack to v5 and webpack-related packages to their latest versions
- update babel eslint-parser
- update jest to v27 (not latest version) and jest-related packages to their latest versions
- use core-js instead of @babel/polyfill
- alter config params to work with newer package versions
## Issue Linkage
Closes #1164
## PR Dependency
Depends on: N/A
## Automated Testing
N/A

### CODE REVIEW

**Comment by legendword** [comment]
`npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated` is caused by @testing-library/jest-dom@5.16.4 (newest version) depending on css@3.0.0 (newest version).
This issue hopefully will get addressed in the next release of the css package (see https://github.com/reworkcss/css/issues/163).

**Comment by legendword** [comment]
Using a combination of core-js and regenerator runtime instead of @babel/polyfill as per the instructions laid out at the top of the page here: https://babeljs.io/docs/en/babel-polyfill
**Note: regenerator runtime is currently not required (tested without it and webpack still worked) because the current babel version is not yet 7.18.0, but once that does happen, regenerator runtime will be required and we would have to test that it works.** Current implementation of regenerator runtime is by using the `useBuiltIns: "usage"` option in @babel/preset-env config.

**Comment by legendword** [comment]
This warning can be safely ignored; it is used by bootstrap.

`npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1`

**Comment by legendword** [comment]
Just waiting for #1116 to be merged for making sure the two warnings are gone. Other than that this PR is done.

**Comment by legendword** [comment]
> * uuid@3.4.0 is depended upon by @cypress/code-coverage@3.9.12
> * querystring@0.2.0 is depended upon by cypress@5.3.0
> 
> Both warning messages may possibly be resolved by merging #1116 which upgrades cypress version.

Apparently, the updated cypress packages are still depending on these deprecated packages.

**Review by zifgu — APPROVED** [review]
Confirming that tests passed locally, npm install worked perfectly as described and there are no longer any warnings. The code changes look good to me.

Note to any future testers/users, I needed to restart the VSCode ESLint plugin, but after doing this, everything worked.

**Pull request merged**
